[package]
name = "docker-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "docker"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.68"
dirs = "4.0.0"
